### ISSUE TITLE
Plugin Development - Paid Job

### ISSUE THREAD

**Issue by alexbgameson** [JackMD/Sell#1]
I would like to pay you to update legacy plugins to API 3.0.0Alpha9.

Interested?

**Comment by JackMD** [comment]
Legacy plugins?

**Comment by alexbgameson** [comment]
Yes, like FactionsPro for example.

**Comment by alexbgameson** [comment]
I will pay you $5 per plugin you update. I have a list I want to give you.

So interested?

**Comment by JackMD** [comment]
Contact me on Twitter :  @JackMTaylor_

**Comment by alexbgameson** [comment]
Ok.

**Comment by alexbgameson** [comment]
Are you sure thats your @?  There isnt a user with that @.   Please message me Check out Alex B (@AlexBGames): https://twitter.com/AlexBGames?s=09
